spring:
  profiles:
    active: dev #使用开发环境配置

---
  
server:
  port: 4001
spring:
  profiles: dev  #开发环境
  application:
    name: luzheng-config-dev
    
---
server:
  port: 4002
spring:
  profiles: prod #生产环境
  application:
    name: luzheng-config-prod