
spring:
  application:
    name: luzheng-usermanagerment-8080
  profiles: dev   #开发环境
server:
  port: 8080
  datasource:
    druid:
      username: root
      password: hoslib123
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/user_manament?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&failOverReadOnly=false


  thymeleaf:
    prefix: classpath:/templates/ #prefix：指定模板所在的目录
    check-template-location: true  #check-tempate-location: 检查模板路径是否存在
    cache: false  #cache: 是否缓存，开发模式下设置为false，避免改了模板还要重启服务器，线上设置为true，可以提高性能。
    suffix:  .*
    #encoding: UTF-8
    #content-type: text/html
    mode: LEGACYHTML5

  mybatis:
    configuration:
      map-underscore-to-camel-case: true

---
spring:
  application:
    name: luzheng-usermanagerment-8080
  profiles: prod   #生产环境
server:
  port: 8080
  datasource:
    druid:
      username: root
      password: hoslib123
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/user_manament?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&failOverReadOnly=false


  thymeleaf:
    prefix: classpath:/templates/ #prefix：指定模板所在的目录
    check-template-location: true  #check-tempate-location: 检查模板路径是否存在
    cache: false  #cache: 是否缓存，开发模式下设置为false，避免改了模板还要重启服务器，线上设置为true，可以提高性能。
    suffix:  .*
    #encoding: UTF-8
    #content-type: text/html
    mode: LEGACYHTML5

  mybatis:
    configuration:
      map-underscore-to-camel-case: true
